spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: lab_531621771
    password: 29c8e3bea06d_#@Aa
    url: jdbc:mysql://rm-bp1oo27t8762xhlob0o.mysql.rds.aliyuncs.com:3306/rds_mysql_15312niv
